# Required to run your project under the correct environment
language: php

# Versions of PHP you want your project run with
php:
  - 7.4
  - 8.0
  - 8.1

# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true
  include:
    - php: 7.4
    - php: 8.0
    - php: 8.1

# Update composer
before-install:
  - composer self-update

# Install composer dependencies, init codeception
install:
  - composer install --no-interaction --dev
  - composer test-init

# Run script
script:
  - composer test
  - composer codesniffer
